[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-C",
    "link-arg=--max-memory=4294967296",
]
runner = 'wasm-bindgen-test-runner'

[unstable]
build-std = ["panic_abort", "std"]

[build]
target = "wasm32-unknown-unknown"
